name: szakdolgozat_mobil_driver_side
description: "Kiss Máté szakdolgozat sofőr oldal"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  dio: ^5.4.0
  socket_io_client: ^3.0.1
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.5
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  get_it: ^8.0.2
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.6.1
  logger: ^2.4.0
  flutter_secure_storage: ^9.2.2
  cupertino_icons: ^1.0.8
  google_directions_api: ^0.10.0
  flutter_gen: ^5.8.0
  no_screenshot: ^0.3.1
  connectivity_plus: ^6.1.0
  flutter_background_service: ^5.0.10

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/generated
  integrations:
    flutter_svg: true
  assets:
    exclude:
      - lib/generated/assets.gen.dart
      - lib/generated/fonts.gen.dart

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: lib/assets/fonts/JetBrainsMonoRomanRegular.ttf
          weight: 400